dataset_pattern: /nobackup/users/bmaier/puma/ttbar_v4/TTBar_*npz 
output: /nobackup/users/bmaier/puma/expts/4/64_final_nopuppi_add_4/ 
n_epochs: 200

embedding_size: 64
hidden_size: 64
intermediate_size: 64
feature_size: 11
num_hidden_layers: 3
num_attention_heads: 4
num_encoders: 4
label_size: 1
attention_band: 30

batch_size: 128 
grad_acc: 16
mask_charged: False
lr: 0.001
lr_decay: 0.97
lr_policy: 'cyclic'
num_max_files: 10
num_max_particles: 9000
#min_met: 50
plot: /nobackup/users/bmaier/scan4/64_final_nopuppi_add_4/
pt_weight: True
#beta: True

epoch_offset: 142
from_snapshot: /nobackup/users/bmaier/puma/expts/4/64_final_nopuppi_add_3/2020_07_12_12_46_45/model_weights_epoch142.pt



