dataset_pattern: /nobackup/users/sidn/puma/merged_v4/merged*npz 
checkpoint_path: /nobackup/users/sidn/puma/expts/4/global_v0
n_epochs: 100

embedding_size: 128 
hidden_size: 128 
intermediate_size: 512 
feature_size: 11 
num_hidden_layers: 6 
num_hidden_groups: 3
inner_group_num: 1
num_attention_heads: 8
label_size: 1
num_global_objects: 60 
attention_band: 30

met_constraint: 0
batch_size: 96 
grad_acc: 8
mask_charged: True 
lr: 0.0005
lr_decay: 0.97
lr_policy: linear 
num_max_files: 1 
num_max_particles: 9000
#min_met: 50
plot: /nobackup/users/sidn/puma/plots/4/global_v0/train/ 
pt_weight: 2
#beta: True
amp: False 
