#dataset_pattern: /nobackup/users/sidn/puma/merged_v4/merged*npz 
dataset_pattern: /nobackup/users/sidn/puma/split_v4/TT*npz 
checkpoint_path: /nobackup/users/sidn/puma/expts/4/global_v0_tt
n_epochs: 100

embedding_size: 64 
hidden_size: 64
intermediate_size: 64 
feature_size: 11 
num_hidden_layers: 12 
num_hidden_groups: 4
inner_group_num: 1
num_attention_heads: 4
label_size: 1
num_global_objects: 60 
attention_band: 30 

met_constraint: 0
batch_size: 128 
grad_acc: 8
mask_charged: True 
opt: adam
lr: 0.001
lr_decay: 0.97
lr_policy: cyclic 
num_max_files: 1 
num_max_particles: 9000
#min_met: 50
plot: /nobackup/users/sidn/puma/plots/4/global_v0_tt/train/ 
pt_weight: 2
#beta: True
amp: False 
