dataset_pattern: /nobackup/users/sidn/puma/merged_v4/merged*npz 
checkpoint_path: /nobackup/users/sidn/puma/expts/4/linear_unshared_v2
n_epochs: 100

embedding_size: 128 
hidden_size: 256 
intermediate_size: 1024 
feature_size: 11 
num_hidden_layers: 12
num_hidden_groups: 12
inner_group_num: 1
num_attention_heads: 8
label_size: 1
#attention_band: 30

met_constraint: 0
batch_size: 64 
grad_acc: 8
mask_charged: True 
lr: 0.0005
lr_decay: 0.97
lr_policy: linear 
num_max_files: 1 
num_max_particles: 9000
#min_met: 50
plot: /nobackup/users/sidn/puma/plots/4/linear_unshared_v2/train/ 
pt_weight: 2
#beta: True
