dataset_pattern: /nobackup/users/sidn/puma/ttbar_v3/TTBar_*npz 
output: /nobackup/users/sidn/puma/expts/3/256_6_20_16_mse/ 
n_epochs: 100

embedding_size: 256
hidden_size: 256
intermediate_size: 256
feature_size: 12 
num_hidden_layers: 1 
num_attention_heads: 4
num_encoders: 6
label_size: 1
attention_band: 32

batch_size: 1024 
grad_acc: 64
mask_charged: True 
lr: 0.0005
lr_decay: 0.9
lr_policy: 'cyclic'
num_max_files: 1 
num_max_particles: 8000
#min_met: 50
plot: /nobackup/users/sidn/scan3/256_6_20_16_mse/
pt_weight: True
#beta: True
